# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Count In' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Toast', '~> 3.0'
  pod 'KLCPopup', '~> 1.0'

  target 'Count InTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Count InUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
